### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by jestxfot** [Jpinsoft/DeepSound#1]
![image](https://github.com/Jpinsoft/DeepSound/assets/87380272/cb4db8b3-1576-47d5-ad09-34c3f864c123)

**Comment by Jpinsoft** [comment]
Hi, this is strange behaviour but if you need previous install package (DeepSoundSetup.msi) you can download it from [direct release 2.0 link](https://github.com/Jpinsoft/DeepSound/releases/download/v2.0.0.32372/DeepSoundSetup.msi)

**Comment by jestxfot** [comment]
The installer did require version 2.0. After I specified the path to it, the installation was successful. Thanks ^^

![image](https://github.com/Jpinsoft/DeepSound/assets/87380272/bcd711fb-ff54-48f9-a210-68c88aa68e95)

**Comment by Jpinsoft** [comment]
Thank for your feedback . I am closing this issue.
